### ISSUE TITLE
Users can apply to a project.

### ISSUE THREAD

**Issue by mtso** [chingu-voyages/v37-bears-team-14#14]
**__Description__**

This epic is for the ability of users to apply to a project.

**__Major User Stories/tasks__**
- [x] Create Application model
- [x] Create Application backend API
- [x] Add button for user to apply to project in project page (maybe header)
- [x] #16 
- [x] Add page for managing an application (accepting or rejecting; allowed for a project owner only)
- [x] #59

#### Functionality
- Users should be able to apply to projects that they are not members of.
- Users should be able to view a list of applications to projects that they own, and manage the status (accept/reject) for them
- Users should be able to view a list of their applications to various projects (`/applications` path)

#### Mockups

<img width="474" alt="Screen Shot 2022-02-26 at 10 26 45 PM" src="https://user-images.githubusercontent.com/8432061/155871113-852345c9-d14a-43ef-9717-601715fc17ca.png">

<img width="472" alt="Screen Shot 2022-02-26 at 10 26 54 PM" src="https://user-images.githubusercontent.com/8432061/155871116-eb6c649e-04c2-409c-b90d-ac407b707bda.png">
