### ISSUE TITLE
Step 1: 🤝 Meet your team & schedule Kickoff meeting

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v37-bears-team-14#4]
**__Task Description__**
- [ ] Meet your team by adding your introduction to the Team Channel
- [ ] Start getting to know one another
- [ ] Start discussing what projects you would like to create
- [ ] Watch the [Voyage Team Roles](https://youtu.be/f_TzehtBliE) video to learn about the different roles members of your team may have signed up to fill.
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/f_TzehtBliE)
- [ ] Watch the [How to Select a Voyage Project](https://youtu.be/5Xv0C5VAKZc) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/5Xv0C5VAKZc)

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Meet Your team (Chingu Handbook)](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#80002162d0284efe81c5d79fca95393d)

Use [When2Meet](https://when2meet.com) to identify days & times when everyone on the team is available to meet.

**Member of Epic:** #16

**Comment by mtso** [comment]
i posted this in the team discord channel but putting it here too https://www.when2meet.com/?14441124-2iMAI
