### ISSUE TITLE
Step 7: ⚙️ Set Up a Team Workflow

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v37-bears-team-14#9]
**__Task Description__**
- [x] Decide on the coding standards the team must follow.
- [x] Define the characteristics of your repo including the number of branches, branch names, & the workflow everyone must follow.
- [x] Agree on the format of commit messages, how Pull Requests will be reviewed, and GitHub branch protection rules.
- [x] Decide on where you’ll deploy your app and the branch to be considered as ‘production’ you’ll be deploying from.
- [ ] Decide on what meetings you’ll need each week and to save time, schedule them as recurring meetings. You might want to look ahead to [Reaching your MVP](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#d0a08743c9c14f7484758d9d7f1e8c8d) to learn more about the types of meetings you’ll need.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Setup Your Team Workflow (Chingu Handbook)](https://www.notion.so/Voyages-8d8e16a5f86e42a88d9ace16bc555f18#9f23ab5ac5e9488a99fb4410bcd33f95)
[Javascript Style Guides](https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa)
[Defining a Git Workflow (Chingu Handbook)](https://www.notion.so/Git-Workflow-6716268427e4458a9a4bfc7d43c4faff)
[Git Branches (Chingu Handbook)](https://www.notion.so/Git-Branches-f419e63959524c8a8583411ffb15acce)
[Git Commits (Chingu Handbook)](https://www.notion.so/Git-Commits-afcdb629e8984a60b555bfb57f665b9f)
[Git Pull Requests (Chingu Handbook)](https://www.notion.so/Git-Pull-Requests-680910fd323748ffaff5d9be308fc0a8)

**Member of Epic:** #16
